apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'tgi-server'
        metrics_path: /metrics
        static_configs:
          - targets: ['tgi.shared-llm.svc.cluster.local:80']

      - job_name: 'proxy-server'         # 🆕 Add this
        metrics_path: /metrics
        static_configs:
          - targets: ['host.docker.internal:3001']  # 🆕 
